### ISSUE TITLE
Implementar Sistema de Login

### ISSUE THREAD

**Issue by sant0ro** [UIoT/uiot_ux#18]
=> Deverá ser programado o sistema de login
+ Implementar As Ações da Controladora Login (Erros de Login, Etc)

**Comment by sant0ro** [comment]
@igorsgm Irei ajudar você nisso.

**Comment by sant0ro** [comment]
The login system is wisely connected with @giovanifss Security Approach. After the Security concepts and artifacts being ready, we can start the communication "session".

As i discussed with @CaioMeloSilva, UIMS will identify itself by the "end-user" connection, that means the user identification is given as a hashed key, in locally (standalone) UIMS instance. With the key (depending how will be the security implementation) the UIMS authenticates with the instance key. (regarding that the key is a identification of that local instanced UIMS, and not the individual user authentication.), regarding that RAISE will only answer the data that this key is allowed to access.

Example: if i don't have access to see any device data, the request to raise/devices/ will return to me an empty object. Or if i have access to only specific data, only this interval will be answered to me. 

Is important that @pedroluizmcs know the final security implementation, since at least the service layer team will implement the approach. As the UIMS uses a library called HTTPful (http://phphttpclient.com/), that @CaioMeloSilva also likes. Is good to implement also in RAISE as the REST communication engine.

Ending report.

**Comment by giovanifss** [comment]
Actually @sant0ro , the application layer is totally out of scope for this first work in security. I do agree that security is crucial for this part, but I think you should implement even without security rules now. If you decide to wait for security standards, this implementation will not be completed in Cycle Aurora.

**Comment by sant0ro** [comment]
Yes, as i argued, the text i wrote ahead, that these ideas is for future. The App Layer team already coding without security. I'm only saying ideas for future. Since i don't know how will be the security implementation. If i didn't wrote clearly that this is an idea for future i'm apologizing now..

**Comment by giovanifss** [comment]
@sant0ro No problem, I understood that you were expecting security work in login for now. Now it's clear. Good work!
