### ISSUE TITLE
Documentações de Classe/Função PhPDoc

### ISSUE THREAD

**Issue by sant0ro** [UIoT/uiot_ux#7]
=> Realizar uma documentação melhor de todas variáveis, funções, classes, possivelmente escrevendo a descrição de cada método, tipo de cada variável, indução de objeto de cada variável, e uso adequado das funções.

=> Realizar documentação de uso.

**Comment by sant0ro** [comment]
@pedroluizmcs @alessandrams @igorsgm Alguém da parte de Documentação poderia ajudar?

**Comment by sant0ro** [comment]
Included in #6

The Documentation and ChangeLog Documentation will be provided in PhPDocumentator (http://phpdoc.org) and GithubChangelog Generator (https://github.com/skywinder/Github-Changelog-Generator)

Citing @igorsgm here.

**Comment by igorsgm** [comment]
Corrigindo as issues de camelCase e colocando as intruções de execução conforme o PHPDocumentator
